### ISSUE TITLE
Occurred SQLException  at Connection#setReadOnly(true)

### ISSUE THREAD

**Issue by btshimizukza** [terasolunaorg/terasoluna-tourreservation#163]
**[Stack Trace]**

```text
org.postgresql.util.PSQLException: Cannot change transaction read-only property in the middle of a transaction.
	at org.postgresql.jdbc2.AbstractJdbc2Connection.setReadOnly(AbstractJdbc2Connection.java:741) ~[postgresql-9.3-1102-jdbc41.jar:na]
	at org.apache.commons.dbcp2.DelegatingConnection.setReadOnly(DelegatingConnection.java:558) ~[commons-dbcp2-2.0.1.jar:2.0.1]
	at org.apache.commons.dbcp2.DelegatingConnection.setReadOnly(DelegatingConnection.java:558) ~[commons-dbcp2-2.0.1.jar:2.0.1]
	at net.sf.log4jdbc.ConnectionSpy.setReadOnly(ConnectionSpy.java:374) ~[log4jdbc-remix-0.2.7.jar:na]
	at org.springframework.jdbc.datasource.DataSourceUtils.prepareConnectionForTransaction(DataSourceUtils.java:155) [spring-jdbc-4.1.3.RELEASE.jar:4.1.3.RELEASE]
	at org.springframework.orm.jpa.vendor.HibernateJpaDialect.beginTransaction(HibernateJpaDialect.java:147) [spring-orm-4.1.3.RELEASE.jar:4.1.3.RELEASE]
	at org.springframework.orm.jpa.JpaTransactionManager.doBegin(JpaTransactionManager.java:380) [spring-orm-4.1.3.RELEASE.jar:4.1.3.RELEASE]
	at org.springframework.transaction.support.AbstractPlatformTransactionManager.getTransaction(AbstractPlatformTransactionManager.java:373) [spring-tx-4.1.3.RELEASE.jar:4.1.3.RELEASE]
	at org.springframework.transaction.interceptor.TransactionAspectSupport.createTransactionIfNecessary(TransactionAspectSupport.java:439) [spring-tx-4.1.3.RELEASE.jar:4.1.3.RELEASE]
	at org.springframework.transaction.interceptor.TransactionAspectSupport.invokeWithinTransaction(TransactionAspectSupport.java:262) [spring-tx-4.1.3.RELEASE.jar:4.1.3.RELEASE]
	at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:96) [spring-tx-4.1.3.RELEASE.jar:4.1.3.RELEASE]
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179) [spring-aop-4.1.3.RELEASE.jar:4.1.3.RELEASE]
	...
	at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:207) [spring-aop-4.1.3.RELEASE.jar:4.1.3.RELEASE]
	at com.sun.proxy.$Proxy34.findOne(Unknown Source) [na:na]
	at org.terasoluna.tourreservation.domain.service.tourinfo.PriceCalculateSharedServiceImpl.loadAges(PriceCalculateSharedServiceImpl.java:61) [terasoluna-tourreservation-domain-1.1.0-SNAPSHOT.jar:na]
	...

```

- [x] reflect master
- [x] reflect mybatis3/master
- [x] resolve an error on startup
- [x] reflect mybatis3/master error on startup

**Comment by btshimizukza** [comment]
@btizumiday 

Please remove `readOnly = true` attribute from find method.
If has been defined the `@Transactional` (not specify `readOnly = true` attribute) at the class level, please remove the `@Transactional` from method level.

**Comment by btshimizukza** [comment]
@btizumiday 

Thank you for resolve.
Please resolve a error at startup.
