### ISSUE TITLE
add wait time before press button

### ISSUE THREAD

**Issue by btyanagawamg** [terasolunaorg/terasoluna-tourreservation#508]
## Description

In travis, there was rare error happens because of trying to press button before displaying the screen. (https://api.travis-ci.org/jobs/269442869/log.txt?deansi=true )

The test case which error happened is [TokenCheckErrorTest#testTourSearchRegistToken](https://github.com/terasolunaorg/terasoluna-tourreservation-mybatis3/blob/5.0.x/terasoluna-tourreservation-selenium/src/test/java/org/terasoluna/tourreservation/tourreserve/selenium/TokenCheckErrorTest.java#L151)
Error log is below.
```
testTourSearchRegistToken(org.terasoluna.tourreservation.tourreserve.selenium.TokenCheckErrorTest)  Time elapsed: 35.734 sec  <<< ERROR!
org.openqa.selenium.NoSuchElementException: Unable to locate element: {"method":"id","selector":"searchTourBtn"}
Command duration or timeout: 30.08 seconds
For documentation on this error, please visit: http://seleniumhq.org/exceptions/no_such_element.html
Build info: version: '2.46.0', revision: '61506a4624b13675f24581e453592342b7485d71', time: '2015-06-04 10:22:50'
System info: host: 'testing-docker-bc9f6de4-2ea9-4dff-abcb-6244e64fd76f', ip: '172.17.0.11', os.name: 'Linux', os.arch: 'amd64', os.version: '4.11.6-041106-generic', java.version: '1.8.0_131'
Driver info: org.openqa.selenium.firefox.FirefoxDriver
Capabilities [{applicationCacheEnabled=true, rotatable=false, handlesAlerts=true, databaseEnabled=true, version=38.8.0, platform=LINUX, nativeEvents=false, acceptSslCerts=true, webStorageEnabled=true, locationContextEnabled=true, browserName=firefox, takesScreenshot=true, javascriptEnabled=true, cssSelectorsEnabled=true}]
Session ID: f965b19c-15bd-462f-8f51-f7eee64de33c
*** Element info: {Using=id, value=searchTourBtn}
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at org.openqa.selenium.remote.ErrorHandler.createThrowable(ErrorHandler.java:204)
	at org.openqa.selenium.remote.ErrorHandler.throwIfResponseFailed(ErrorHandler.java:156)
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:605)
	at org.openqa.selenium.remote.RemoteWebDriver.findElement(RemoteWebDriver.java:358)
	at org.openqa.selenium.remote.RemoteWebDriver.findElementById(RemoteWebDriver.java:399)
	at org.openqa.selenium.By$ById.findElement(By.java:215)
	at org.openqa.selenium.remote.RemoteWebDriver.findElement(RemoteWebDriver.java:350)
	at org.terasoluna.tourreservation.tourreserve.selenium.TokenCheckErrorTest.testTourSearchRegistToken(TokenCheckErrorTest.java:151)
Caused by: org.openqa.selenium.NoSuchElementException: Unable to locate element: {"method":"id","selector":"searchTourBtn"}
For documentation on this error, please visit: http://seleniumhq.org/exceptions/no_such_element.html
Build info: version: '2.46.0', revision: '61506a4624b13675f24581e453592342b7485d71', time: '2015-06-04 10:22:50'
System info: host: 'testing-docker-bc9f6de4-2ea9-4dff-abcb-6244e64fd76f', ip: '172.17.0.11', os.name: 'Linux', os.arch: 'amd64', os.version: '4.11.6-041106-generic', java.version: '1.8.0_131'
```

## Possible Solutions

One possible solution I can propose is putting wait appropriate time or checking the display screen is fine before checking the screen elements.
Please see similar issue([terasoluna-gfw-functionaltest #675](https://github.com/terasolunaorg/terasoluna-gfw-functionaltest/issues/675)) comment.
And there may be other solution.

## Affects Version/s
* 5.X.X.RELEASE
* 1.X.X.RELEASE

## Fix Version/s
- [ ] 5.4.0 (master)
- [ ] 5.3.1 (5.3.x)
- [ ] 5.2.2 (5.2.x)
- [ ] 5.1.2 (5.1.x)
- [ ] 5.0.3 (5.0.x)
- [ ] 1.0.7 (1.0.x)

## Final Solution
(To be written later by project member)

## Issue Links
* [terasoluna-gfw-functionaltest #675](https://github.com/terasolunaorg/terasoluna-gfw-functionaltest/issues/675)

**Comment by itouyun** [comment]
Should we add `assertThat(driver.getTitle(), is("@@@Screen name@@@"));` after all `click` method ...?
many many modify points...

**Comment by yoshikawaa** [comment]
It has not occurred for a long time.
